---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - controller.kubehoist.io
  resources:
  - controllerwatches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controller.kubehoist.io
  resources:
  - controllerwatches/finalizers
  verbs:
  - update
- apiGroups:
  - controller.kubehoist.io
  resources:
  - controllerwatches/status
  verbs:
  - get
  - patch
  - update
